### ISSUE TITLE
건의사항

### ISSUE THREAD

**Issue by eondcom** [wstackme/wst_add_admin_favorite#1]
1. 이름(주소) 보다
이름, 주소
이런 형식이 나아보입니다.

2. 새창옵션이 있으면 어떨까요?;;

ps. 이 애드온은 어떤 의도로 만드신 건지 궁금합니다. ^^;

**Comment by nemo9l** [comment]
1. 설정 방식에 대해서는 조금 더 고민을 해 볼 필요가 있어보입니다.
2. 새창 옵션은 추가하도록 하겠습니다.

+. 그저 '새탭 후 주소입력' 이 귀찮았을 뿐입니다...! ^^;
